version: '2'

services:
  app:
    image: registry.open-web.nl:5043/wio-link-client-core-demo:0.1.0-SNAPSHOT
#    ports:
#    - "8080:8080"
    environment:
      spring.data.elasticsearch.cluster-name: "elasticsearch"
      spring.data.elasticsearch.cluster-nodes: "elasticsearch:9300"
      wio.username: "username"
      wio.password: "password"
    restart: always