version: '2'

services:
  app:
    image: registry.open-web.nl:5043/wio-link-client-core-monitor-demo:0.1.0-SNAPSHOT
    ports:
    - "8080:8080"
    environment:
      spring.data.elasticsearch.cluster-name: "elasticsearch"
      spring.data.elasticsearch.cluster-nodes: "elasticsearch:9300"
      wio.username: "username"
      wio.password: "password"
      wio.monitor.node-names: ""
    restart: always
  elasticsearch:
    image: elasticsearch:2.4.4
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx1g"
    ports:
      - "9200:9200"
#      - "9300:9300"
    restart: always
  kibana:
    image: kibana:4.6.4
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    restart: always
volumes:
  elasticsearch_data:
    driver: local